language:
  - swift
osx_image: xcode10.1

before_script:
- cd CardSlidingView

before_install:
- gem install cocoapods # Since Travis is not always on latest version

script:
  - pod install
  - xcodebuild -scheme CardSlidingView -workspace CardSlidingView.xcworkspace -sdk iphonesimulator clean build -enableCodeCoverage YES test

after_script:
  - bash <(curl -s https://codecov.io/bash) -X xcodellvm
  - bash <(curl -s https://codecov.io/bash) -t 07e07e95-fa0e-46e8-bc64-69c58df279ea
  
after_success:
    - bash <(curl -s https://codecov.io/bash)
