language:
  - swift
osx_image: xcode10.1
script:
  - xcodebuild -scheme CardSlidingView -workspace ./CardSlidingView/CardSlidingView.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build
after_success:
  - bash <(curl -s https://codecov.io/bash)
