language:
  - swift
osx_image: xcode10.1
script:
  - xcodebuild -scheme CardSlidingView -workspace './CardSlidingView/CardSlidingView.xcworkspace' clean build
after_success:
  - bash <(curl -s https://codecov.io/bash)
