language:
  - swift
osx_image: xcode10.1

before_script:
- cd CardSlidingView

before_install:
- gem install cocoapods # Since Travis is not always on latest version

script:
  - pod install
  - xcodebuild -scheme CardSlidingView -workspace CardSlidingView.xcworkspace -sdk iphonesimulator clean build -enableCodeCoverage YES test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
