language:
  - swift
osx_image: xcode10.1

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install

script:
  - xcodebuild -scheme CardSlidingView -workspace './CardSlidingView/CardSlidingView.xcworkspace' clean build
after_success:
  - bash <(curl -s https://codecov.io/bash)
