# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'CardSlidingView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardSlidingView
  pod 'SDWebImage'
end

target 'CardSlidingViewTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for CardSlidingView
  pod 'SDWebImage'
end
